export enum ActivityType {
  REQUISITION_CREATE = "REQUISITION_CREATE",
  REQUISITION_UPDATE = "REQUISITION_UPDATE",
  REQUISITION_APPROVE = "REQUISITION_APPROVE",
  REQUISITION_HOLD = "REQUISITION_HOLD",
  RECRUITER_ASSIGNED = "RECRUITER_ASSIGNED",
  RECRUITER_UNASSIGNED = "RECRUITER_UNASSIGNED",
  JOB_PUBLISHED = "JOB_PUBLISHED",
  JOB_UNPUBLISHED = "JOB_UNPUBLISHED",
  CANDIDATE_SCHEDULED = "CANDIDATE_SCHEDULED", // CANDIDATE INTERVIEW SCHEDULED
  CANDIDATE_APPLICATION = "CANDIDATE_APPLICATION", // NEW CANDIDATE APPLIED FOR THE JOB
  OFFER_REVISION = "OFFER_REVISION", // CANDIDATE IS REQUESTING OFFER REVISION
  CANDIDATE_HIRED = "CANDIDATE_HIRED", // CANDIDATE IS HIRED
}

export interface Activity {
  activity_id: string;
  triggered_by_id: string;
  triggered_by_name: string;
  triggered_action: ActivityType | string;
  triggered_at: string;
  target_id: string;
  target_name: string;
  additional_info: string;
  target_type: string;
}
